application:
  layer: "development"

app_alerts_proxy:
  fake: true

bearfacts_proxy:
  fake: true

blog_latest_release_notes_feed_proxy:
  fake: true

cache:
  store: "memory"
  log_level: <%= Logger::DEBUG %>

cal_link_proxy:
  fake: true

canvas_proxy:
  fake: true

cas_server: 'https://auth-test.berkeley.edu/cas'
cas_logout_url: 'https://auth-test.berkeley.edu/cas/logout'

financials_proxy:
  fake: true

textbooks_proxy:
  fake: true

google_proxy:
  fake: true

logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || true %>
  slow_query_threshold_in_ms: 2000

myfinaid_proxy:
  fake: true

cal1card_proxy:
  fake: true

postgres:
  database: <%= ENV['DB_ENV_POSTGRESQL_DB'] || 'calcentral_development' %>
  username: <%= ENV['DB_ENV_POSTGRESQL_USER'] || 'calcentral_development' %>
  password: <%= ENV['DB_ENV_POSTGRESQL_PASS'] || 'secret' %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || '5432' %>

campusdb:
  fake: true

ist_jms:
  fake: true
  enabled: false

hot_plate:
  enabled: false

features:
  my_fin_aid: true
  textbooks: true
  videos: true
  cal1card: true
  reauthentication: false
  audio: true
  advising: true
  course_manage_official_sections: true
  cs_fin_aid: true
  cs_profile: true
  cs_sir: true
  prevent_acting_as_users_from_posting: false
  show_notifications_archive_link: true

advising_proxy:
  fake: true
