application:
  layer: "development"

app_alerts_proxy:
  fake: true
  base_url: "http://ets-dev.berkeley.edu/calcentral-alerts/feed"

bearfacts_proxy:
  fake: true

blog_latest_release_notes_feed_proxy:
  fake: true

cache:
  store: "memory"
  log_level: <%= Logger::DEBUG %>
  expiration:
    default: <%= 35.minutes %>
    MyAcademics::Merged: <%= 1.day %>
    MyActivities: <%= 1.day %>
    MyBadges::Merged: <%= 1.day %>
    MyCampusLinksController: <%= 1.day %>
    MyClasses::Merged: <%= 1.day %>
    Financials::MyFinancials: <%= 1.day %>
    Finaid::MyFinAid: <%= 1.day %>
    Cal1card::MyCal1card: <%= 1.day %>
    MyGroups::Merged: <%= 1.day %>
    MyTasks::Merged: <%= 1.day %>
    UpNext::MyUpNext: <%= 1.day %>
    User::Api: <%= 1.day %>

cal_link_proxy:
  fake: true

canvas_proxy:
  fake: true

cas_server: 'https://auth-test.berkeley.edu/cas'
cas_logout_url: 'https://auth-test.berkeley.edu/cas/logout'

financials_proxy:
  fake: true

textbooks_proxy:
  fake: true

google_proxy:
  fake: true

logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || true %>
  slow_query_threshold_in_ms: 2000

myfinaid_proxy:
  fake: true

cal1card_proxy:
  fake: true

postgres:
  database: <%= ENV['DB_ENV_POSTGRESQL_DB'] || 'calcentral_development' %>
  username: <%= ENV['DB_ENV_POSTGRESQL_USER'] || 'calcentral_development' %>
  password: <%= ENV['DB_ENV_POSTGRESQL_PASS'] || 'secret' %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || '5432' %>

sakai_proxy:
  fake: true

ist_jms:
  fake: true
  enabled: false

hot_plate:
  enabled: false

features:
  my_fin_aid: true
  textbooks: true
  videos: true
  cal1card: true
  reauthentication: false
  audio: true
  advising: true
  course_manage_official_sections: true

advising_proxy:
  fake: true
