# The test environment should require minimal configuration, and is the one targeted by travis.
# Avoid creating too many dependencies (if any) on a test.local.yml
logger:
  level: <%= ENV['LOGGER_LEVEL'] || DEBUG %>
  stdout: <%= ENV['LOGGER_STDOUT'] || 'only' %>
application:
  layer: "test"
canvas_proxy:
  fake: true
  app_provider_host: 'https://cc-dev.example.com'
ldap:
  host: 'nds-test.berkeley.edu'
google_proxy:
  fake: true
financials_proxy:
  fake: true
textbooks_proxy:
  fake: true
terms:
  # Keyed to H2 test data
  fake_now: 2013-10-11 04:20:00
sakai_proxy:
  fake: false
  # Keyed to H2 test data
  fake_now: 2013-03-11 04:20:00
cal_link_proxy:
  fake: true
cal1card_proxy:
  fake: true
calmail_proxy:
  fake: true

# To avoid "Illegal key size" errors on systems which we can't modify (e.g., Travis),
# lower the security of the encryption algorithm.
oauth2:
  encryption: "aes-128-cbc"

myfinaid_proxy:
  fake: true

app_alerts_proxy:
  fake: true
  base_url: "http://ets-dev.berkeley.edu/calcentral-alerts/feed"

service_alerts_proxy:
  fake: true
  base_url: 'https://test-ets.pantheon.berkeley.edu/news-archive/calcentral-service-alert/feed'

features:
  bearfacts: true
  financials: true
  telebears: true
  textbooks: true
  videos: true
  cal1card: true
  audio: true
  advising: true
  webcast_sign_up_on_calcentral: true
  service_alerts_rss: true

cache:
  store: "memory"
  log_level: <%= Logger::DEBUG %>
  expiration:
    default: <%= 35.minutes %>
    MyAcademics::Merged: <%= 1.day %>
    MyActivities: <%= 1.day %>
    MyBadges::Merged: <%= 1.day %>
    MyCampusLinks: <%= 1.day %>
    MyClasses::Merged: <%= 1.day %>
    Financials::MyFinancials: <%= 1.day %>
    Finaid::MyFinAid: <%= 1.day %>
    Cal1card::MyCal1card: <%= 1.day %>
    MyGroups::Merged: <%= 1.day %>
    MyTasks::Merged: <%= 1.day %>
    UpNext::MyUpNext: <%= 1.day %>
    User::Api: <%= 1.day %>

advising_proxy:
  fake: true
