-- Students
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73974, 322587,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73974, 192517,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73974, 238382,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73974, 2040,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73974, 191779,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73974, 208861,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73974, 211159,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73980, 322587,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73980, 192517,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73980, 238382,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73980, 2040,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73980, 191779,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73980, 208861,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',73980, 211159,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',86103, 322279,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',86103, 323487,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',86103, 675750,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',86103, 730057,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',86103, 904715,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',86103, 978966,'G','1',5,'E','N ',0,'  ');
Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',86103, 300846,'G','1',5,'E','N ',0,'  ');

-- Instructors
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',73980, 322279,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',73974, 322279,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',73974, 323487,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',73974, 675750,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',73974, 730057,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',73974, 904715,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',73974, 978966,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',86103, 322587,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',86103, 192517,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',86103, 238382,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',86103, 2040,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',86103, 191779,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',86103, 208861,' ','2','1');
Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',86103, 211159,' ','2','1');
