-- Just enough for unit testing. Good UX testing would require a much larger
-- dataset.

Insert into BSPACE_CLASS_ROSTER_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,STUDENT_LDAP_UID,UG_GRAD_FLAG,ROLE_CD,UNIT,ENROLL_STATUS,PNP_FLAG,WAIT_LIST_SEQ_NUM,CREDIT_CD) values (2012,'D',32203,322279,'G','1',5,'E','N ',0,'  ');

Insert into BSPACE_COURSE_INSTRUCTOR_VW (TERM_YR,TERM_CD,COURSE_CNTL_NUM,INSTRUCTOR_LDAP_UID,MULTI_ENTRY_CD,SUB_TERM_CD,INSTRUCTOR_FUNC) values (2012,'D',32203,322587,' ','2','2');
