DROP TABLE IF EXISTS BSPACE_CLASS_ROSTER_VW;
CREATE TABLE BSPACE_CLASS_ROSTER_VW (
"TERM_YR" NUMBER(4),
"TERM_CD" CHAR(1),
"COURSE_CNTL_NUM" NUMBER(5),
"STUDENT_LDAP_UID" NUMBER(10),
"UG_GRAD_FLAG" CHAR(1),
"ROLE_CD" CHAR(1),
"UNIT" NUMBER(3,1),
"ENROLL_STATUS" CHAR(1),
"PNP_FLAG" CHAR(2),
"WAIT_LIST_SEQ_NUM" NUMBER,
"CREDIT_CD" CHAR(2));

DROP TABLE IF EXISTS BSPACE_CLASS_SCHEDULE_VW;
CREATE TABLE BSPACE_CLASS_SCHEDULE_VW(
"TERM_YR" NUMBER(4),
"TERM_CD" CHAR(1),
"COURSE_CNTL_NUM" NUMBER(5),
"MULTI_ENTRY_CD" CHAR(1),
"BUILDING_NAME" VARCHAR2(12),
"ROOM_NUMBER" VARCHAR2(8),
"MEETING_DAYS" VARCHAR2(7),
"MEETING_START_TIME" VARCHAR2(4),
"MEETING_START_TIME_AMPM_FLAG" VARCHAR2(1),
"MEETING_END_TIME" VARCHAR2(4),
"MEETING_END_TIME_AMPM_FLAG" VARCHAR2(1),
"PRINT_CD" VARCHAR2(1));

DROP TABLE IF EXISTS BSPACE_COURSE_INFO_VW;
CREATE TABLE BSPACE_COURSE_INFO_VW(
"TERM_YR" NUMBER(4),
"TERM_CD" CHAR(1),
"COURSE_CNTL_NUM" NUMBER(5),
"DEPT_NAME" VARCHAR2(7),
"CATALOG_ID" VARCHAR2(7),
"CATALOG_PREFIX" VARCHAR2(1),
"CATALOG_ROOT" NUMBER(3),
"CATALOG_SUFFIX_1" VARCHAR2(1),
"CATALOG_SUFFIX_2" VARCHAR2(1),
"PRIMARY_SECONDARY_CD" VARCHAR2(1),
"SECTION_NUM" VARCHAR2(3),
"COURSE_TITLE" VARCHAR2(65),
"LOWER_RANGE_UNIT" NUMBER(3,1),
"UPPER_RANGE_UNIT" NUMBER(3,1),
"VARIABLE_UNIT_CD" VARCHAR2(1),
"FIXED_UNIT" NUMBER(3,1),
"INSTRUCTION_FORMAT" VARCHAR2(3),
"CRED_CD" VARCHAR2(2),
"ENROLL_LIMIT" NUMBER(5),
"CROSS_LISTED_FLAG" VARCHAR2(1),
"INSTR_FUNC" VARCHAR2(1),
"SCHEDULE_PRINT_CD" VARCHAR2(1),
"SECTION_CANCEL_FLAG" VARCHAR2(1),
"COURSE_TITLE_SHORT" VARCHAR2(19),
"CATALOG_DESCRIPTION" VARCHAR2(1300),
"COURSE_OPTION" VARCHAR2(2),
"DEPT_DESCRIPTION" VARCHAR2(35));

DROP TABLE IF EXISTS BSPACE_COURSE_INSTRUCTOR_VW;
CREATE TABLE BSPACE_COURSE_INSTRUCTOR_VW(
"TERM_YR" NUMBER(4),
"TERM_CD" VARCHAR2(1),
"COURSE_CNTL_NUM" NUMBER(5),
"INSTRUCTOR_LDAP_UID" NUMBER(10),
"MULTI_ENTRY_CD" VARCHAR2(1),
"SUB_TERM_CD" VARCHAR2(1),
"INSTRUCTOR_FUNC" VARCHAR2(1));

DROP TABLE IF EXISTS BSPACE_DEPT_VW;
CREATE TABLE BSPACE_DEPT_VW(
"DEPT_NAME" VARCHAR2(7),
"DEPT_DESCRIPTION" VARCHAR2(35),
"CHNG_DATE" DATE,
"DEPT_END_TERM_YR" NUMBER(4),
"DEPT_END_TERM_CD" CHAR(1),
"DEPT_START_TERM_YR" NUMBER(4),
"DEPT_START_TERM_CD" CHAR(1));

DROP TABLE IF EXISTS BSPACE_INSTRUCTOR_INFO_VW;
CREATE TABLE BSPACE_INSTRUCTOR_INFO_VW(
"INSTRUCTOR_LDAP_UID" NUMBER(10),
"INSTRUCTOR_NAME" VARCHAR2(255),
"FIRST_NAME" VARCHAR2(80),
"LAST_NAME" VARCHAR2(80),
"INSTRUCTOR_EMAIL" VARCHAR2(255),
"IS_AFFILIATE" CHAR(1),
"AFFILIATIONS" VARCHAR2(255));

DROP TABLE IF EXISTS BSPACE_PERSON_INFO_VW;
"LDAP_UID" NUMBER,
"STUDENT_ID" NUMBER,
"INSTRUCTOR_FLAG" VARCHAR2(1),
"UG_GRAD_FLAG" VARCHAR2(1),
"PERSON_TYPE" VARCHAR2(1),
"EMAIL_DISCLOS_CD" VARCHAR2(1),
"FIRST_NAME" VARCHAR2(80),
"LAST_NAME" VARCHAR2(80),
"PERSON_NAME" VARCHAR2(255),
"EMAIL_ADDRESS" VARCHAR2(255),
"TELEPHONE" VARCHAR2(30),
"AFFILIATIONS" VARCHAR2(4000),
"KERBEROSPRINCIPALSTRING" VARCHAR2(4000));

DROP TABLE IF EXISTS BSPACE_STUDENT_MAJOR_VW;
CREATE TABLE BSPACE_STUDENT_MAJOR_VW(
"STUDENT_LDAP_UID" NUMBER(10),
"UG_GRAD_FLAG" VARCHAR2(1),
"ROLE_CD" VARCHAR2(1),
"STU_NAME" VARCHAR2(255),
"STUDENT_EMAIL_ADDRESS" VARCHAR2(255),
"EMAIL_DISCLOS_CD" VARCHAR2(1),
"EDUC_LEVEL" VARCHAR2(1),
"FIRST_NAME" VARCHAR2(80),
"LAST_NAME" VARCHAR2(80),
"STUDENT_ID" NUMBER(8),
"AFFILIATIONS" VARCHAR2(255));

DROP TABLE IF EXISTS BSPACE_STUDENT_PHOTO_VW;
CREATE TABLE BSPACE_STUDENT_PHOTO_VW(
"STUDENT_LDAP_UID" NUMBER(10),
"BYTES" NUMBER,
"UPDATE_DATE" DATE,
"PHOTO" BLOB);

-- BSPACE_STUDENT_PORTAL_VW

-- BSPACE_STUDENT_TERM_VW

DROP TABLE IF EXISTS BSPACE_TERM_INFO_VW;
CREATE TABLE BSPACE_TERM_INFO_VW(
"TERM_YR" VARCHAR2(8),
"TERM_CD" CHAR(1),
"SUB_TERM_CD" CHAR(1),
"TERM_STATUS" CHAR(2),
"TERM_STATUS_DESC" CHAR(15),
"AID_YR" CHAR(3),
"TERM_ABBR" CHAR(3),
"TERM_NAME" CHAR(6),
"TERM_CENTURY" CHAR(2),
"CURRENT_TB_TERM_FLAG" CHAR(1),
"TERM_START_DATE" DATE,
"TERM_END_DATE" DATE,
"BSPACE_CURRENT" CHAR(1 CHAR));

DROP TABLE IF EXISTS BSPACE_STUDENT_INFO_VW;
CREATE TABLE BSPACE_STUDENT_INFO_VW(
"STUDENT_LDAP_UID" NUMBER(10),
"UG_GRAD_FLAG" VARCHAR2(1),
"ROLE_CD" VARCHAR2(1),
"STU_NAME" VARCHAR2(255),
"STUDENT_EMAIL_ADDRESS" VARCHAR2(255),
"EMAIL_DISCLOS_CD" VARCHAR2(1),
"EDUC_LEVEL" VARCHAR2(1),
"FIRST_NAME" VARCHAR2(80),
"LAST_NAME" VARCHAR2(80),
"STUDENT_ID" NUMBER(8),
"AFFILIATIONS" VARCHAR2(255));
